version: '3.8'

services:
    mosquitto:
        container_name: magig-mirrow-mqtt
        image: eclipse-mosquitto:latest
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge
